In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('data_orders.csv', index_col='order_id')
df.head()

In [ ]:
# Редактирование колонок 
# df['price'] = df['price'] * 100 # Указыаем колонку и присваеваем новые значения путем какой-нибудь операции
# df['price'] = 0 # То же самое, распространится на все ячейки

In [ ]:
# Редактивроание строк
df.loc[1001] = {'date': '2025-12-31', 'quantity': 3, 'region': 'East', 'product': 'fff', 'price': 1, 'category': 'vvv'} # Указали индекс и передали в него словарь с отредактированными данными, где указывали название колонки и новое значение 
df.loc[1001]

In [ ]:
# Редактирование ячеек
df.at[1002, 'date'] = None # Указали ячейку и записали туда новое значение

In [ ]:
# Редактирование по фильтру 
df.loc[df['quantity'] == 1, 'price'] = df.loc[df['quantity'] == 1, 'price'] * .7 # К отфильтрованной колонки присвоили новые значения, которые получили с помощью операции

In [ ]:
# Добавление колонок 
df['foo'] = 1 # Добовляем новую колонку просто указывая новое имя колонки в дф и присваиваем значения 
df['price_discount'] = df['price'] * .7 # Или делаем новую колонку путем выполнения какой-то операции от другой колонки
df

In [ ]:
# Добавление строк
df.loc[1008] = {} # Указываем новый индекс и присваем либо пустоту, либо указыаем названия колонок и значения 
df

In [ ]:
# Удаление колонок и строк # По сути название и любой строки и любой колонки это - индекс(какой-то)
# df = df.drop('foo', axis='columns') # Указыаем индекс и по какой оси мы хотим сделать удаление
df = df.drop(1008, axis='rows')
# Если нужно удалить несколько строк или колонок, то передаем индексы списком

In [ ]:
df = df.drop_duplicates('date', keep='first') # Так удаляются дубликаты в определенной колонки

,date,product,category,quantity,price,region,price_discount
order_id,,,,,,,
1001,2025-12-31,fff,vvv,3,1,East,0.7
1002,None,Mouse,Electronics,2,25.5,South,17.85
1003,2025-01-02,Desk Chair,Furniture,1,105.0,West,73.5
1004,2025-01-03,Notebook,Stationery,10,5.0,North,3.5
1005,2025-01-04,Monitor,Electronics,1,210.0,East,147.0
1006,2025-01-05,Coffee Table,Furniture,1,140.0,West,98.0

In [ ]:
# Обработка пустых записей
df.dropna() # Удаляем строки с пустыми записями 
df.fillna('foo') # Либо передаем этим строкам какое-то значение

,date,product,category,quantity,price,region,price_discount
order_id,,,,,,,
1001,2025-12-31,fff,vvv,3,1,East,0.7
1003,2025-01-02,Desk Chair,Furniture,1,105.0,West,73.5
1004,2025-01-03,Notebook,Stationery,10,5.0,North,3.5
1005,2025-01-04,Monitor,Electronics,1,210.0,East,147.0
1006,2025-01-05,Coffee Table,Furniture,1,140.0,West,98.0
1007,2025-01-05,Mouse,Electronics,5,25.5,North,17.85

In [77]:
# Обработка датафреймов с помощью функции 'apply()'
# > 1 -> .5
# > 4 -> .3
# > 5 -> .1

def apply_discount(row):
    if row['quantity'] < 1:
        row['quantity'] *= .5
    elif row['quantity'] < 4:
        row['quantity'] *= .3
    else:
        row['quantity'] *= .1
    return row

# test = pd.DataFrame([{'quantity': 7}, {'quantity': 3}, {'quantity': 0.5}])
# # test
# test.apply(apply_discount, axis='columns')
df.head()
# df.apply(apply_discount, axis='columns')

,date,product,category,quantity,price,region,price_discount
order_id,,,,,,,
1001,2025-12-31,fff,vvv,3,1,East,0.7
1002,None,Mouse,Electronics,2,25.5,South,17.85
1003,2025-01-02,Desk Chair,Furniture,1,105.0,West,73.5
1004,2025-01-03,Notebook,Stationery,10,5.0,North,3.5
1005,2025-01-04,Monitor,Electronics,1,210.0,East,147.0

In [78]:
df.apply(apply_discount, axis='columns')

,date,product,category,quantity,price,region,price_discount
order_id,,,,,,,
1001,2025-12-31,fff,vvv,0.9,1.0,East,0.70
1002,None,Mouse,Electronics,0.6,25.5,South,17.85
1003,2025-01-02,Desk Chair,Furniture,0.3,105.0,West,73.50
1004,2025-01-03,Notebook,Stationery,1.0,5.0,North,3.50
1005,2025-01-04,Monitor,Electronics,0.3,210.0,East,147.00
1006,2025-01-05,Coffee Table,Furniture,0.3,140.0,West,98.00
1007,2025-01-05,Mouse,Electronics,0.5,25.5,North,17.85

In [79]:
df.apply(lambda row: row['quantity'] * .3 if row['quantity'] < 4 else row['quantity'], axis='columns')

order_id
1001     0.9
1002     0.6
1003     0.3
1004    10.0
1005     0.3
1006     0.3
1007     5.0
dtype: float64

In [ ]:
# row['quantity'] * .3 if row['quantity'] < 4 else row['quantity'] # Синтаксический сахар, сначала сделаай что-то - если и пошла проверка