In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('ads.csv')
df.head(30)

In [ ]:
# Расходы на каждый рекламный канал в каждой стране 
# Стоимость клика в каждой стране и каждом рекламном канале 
# Данные были читаемыми

In [ ]:
df.pivot_table( # Функция создает свойдну таблицу, указываем ей как хотим, чтобы выглядели строки, колонки, значения и какие функции к ним применить
    index='country',
    columns='ad_channel',
    values=['ad_spend', 'clicks'],
    aggfunc='sum'
).fillna(0) # Функция вместо NaN подставляет 0 в данном случае или можем удалить .dropna()

In [22]:
df.set_index('country').loc['US'][['date', 'ad_channel', 'impressions']]

               date ad_channel  impressions
country
US       2026-01-01  Instagram         7200
US       2026-01-02  Instagram         6850
US       2026-01-03  Instagram         7800
US       2026-01-04  Instagram         7100
US       2026-01-05  Instagram         7400
US       2026-01-06  Instagram         6950
US       2026-01-07  Instagram         7650
US       2026-01-08  Instagram         7300
US       2026-01-09  Instagram         7550
US       2026-01-10  Instagram         7200
US       2026-01-11  Instagram         7450
US       2026-01-12  Instagram         7100
US       2026-01-13  Instagram         7800
US       2026-01-14  Instagram         7350
US       2026-01-15  Instagram         7250
US       2026-01-16  Instagram         7600
US       2026-01-17  Instagram         7050
US       2026-01-18  Instagram         7500
US       2026-01-19  Instagram         7150
US       2026-01-20  Instagram         7400
US       2026-01-21  Instagram         7300
US       2026-01-22  Instagram         7700
US       2026-01-23  Instagram         7200
US       2026-01-24  Instagram         7450
US       2026-01-25  Instagram         7100
US       2026-01-26  Instagram         7550
US       2026-01-27  Instagram         7350
US       2026-01-28  Instagram         7650
US       2026-01-29  Instagram         7200
US       2026-01-30  Instagram         7500
US       2026-01-31  Instagram         7400

In [ ]:
# Функция .pivot(index=, columns=, values=) # По сути нужна чтобы переоформить наш дф в другой вид(Больше строк, меньше колонок или наоборот) 
# От пивот тейбл отличается отсутствием параметра агрегации
(
    df
    .set_index('country')
    .loc['US']
    .pivot(
                        index='date',
                        columns='ad_channel',
                        values='impressions'
)
    .fillna(0)
    .astype('int') # Меняет тип даных в значениях
)

ad_channel  Instagram
date
2026-01-01       7200
2026-01-02       6850
2026-01-03       7800
2026-01-04       7100
2026-01-05       7400
2026-01-06       6950
2026-01-07       7650
2026-01-08       7300
2026-01-09       7550
2026-01-10       7200
2026-01-11       7450
2026-01-12       7100
2026-01-13       7800
2026-01-14       7350
2026-01-15       7250
2026-01-16       7600
2026-01-17       7050
2026-01-18       7500
2026-01-19       7150
2026-01-20       7400
2026-01-21       7300
2026-01-22       7700
2026-01-23       7200
2026-01-24       7450
2026-01-25       7100
2026-01-26       7550
2026-01-27       7350
2026-01-28       7650
2026-01-29       7200
2026-01-30       7500
2026-01-31       7400