In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('daily_visitors_dynamic.csv')
df.head(10)

         date   ad_channel  daily_visitors
0  2026-01-01       google              52
1  2026-01-01     facebook              50
2  2026-01-01      youtube              55
3  2026-01-01    instagram              53
4  2026-01-01  influencers              51
5  2026-01-02       google              54
6  2026-01-02     facebook              52
7  2026-01-02      youtube              57
8  2026-01-02    instagram              55
9  2026-01-02  influencers              53

In [ ]:
# rolling()
df.groupby('date')['daily_visitors'].sum().head(10).rolling(7).mean() # Функция rolling() - Скользящая средная (Rolling Mean / Moving Average) вычисляет среднее значение временного ряда в пределах скользящего окна заданного размера. Это скользящее окно перемещается вдоль временного ряда и в каждой точке времени вычисляет среднее значение точек данных внутри этого окна.
# Прикол роллинга именно в окне, он может выбрать временной окно и посчиать значение за это окно

In [7]:
# transform() # В то время как агрегирующая функция должна возвращать сокращенную версию данных, преобразование может вернуть версию полного набора данных, преобразованную ради дальнейшей их перекомпоновки. При подобном преобразовании форма выходных данных совпадает с формой входных.
# transform сохраняет формат исходного набора данных. Это уникальная особенность transform!

df['total_visitors'] = df.groupby('ad_channel')['daily_visitors'].transform(lambda x: sum(x))
df

           date   ad_channel  daily_visitors  total_visitors  rolling_average
0    2026-01-01       google              52            2472              NaN
1    2026-01-01     facebook              50            2445              NaN
2    2026-01-01      youtube              55            2562              NaN
3    2026-01-01    instagram              53            2515              NaN
4    2026-01-01  influencers              51            2470              NaN
..          ...          ...             ...             ...              ...
150  2026-01-31       google              98            2472        99.142857
151  2026-01-31     facebook             100            2445        99.000000
152  2026-01-31    instagram              99            2515        98.714286
153  2026-01-31      youtube             100            2562        98.714286
154  2026-01-31  influencers              98            2470        99.142857

[155 rows x 5 columns]

In [9]:
df['rolling_average'] = df.groupby('ad_channel')['daily_visitors'].transform(lambda x: x.rolling(7).mean())
df.head(10)

         date   ad_channel  daily_visitors  total_visitors  rolling_average
0  2026-01-01       google              52            2472              NaN
1  2026-01-01     facebook              50            2445              NaN
2  2026-01-01      youtube              55            2562              NaN
3  2026-01-01    instagram              53            2515              NaN
4  2026-01-01  influencers              51            2470              NaN
5  2026-01-02       google              54            2472              NaN
6  2026-01-02     facebook              52            2445              NaN
7  2026-01-02      youtube              57            2562              NaN
8  2026-01-02    instagram              55            2515              NaN
9  2026-01-02  influencers              53            2470              NaN

In [14]:
df.sort_values(['ad_channel', 'date']).head(20)

          date ad_channel  daily_visitors  total_visitors  rolling_average
1   2026-01-01   facebook              50            2445              NaN
6   2026-01-02   facebook              52            2445              NaN
11  2026-01-03   facebook              54            2445              NaN
16  2026-01-04   facebook              56            2445              NaN
21  2026-01-05   facebook              58            2445              NaN
27  2026-01-06   facebook              60            2445              NaN
31  2026-01-07   facebook              62            2445             56.0
37  2026-01-08   facebook              64            2445             58.0
42  2026-01-09   facebook              66            2445             60.0
46  2026-01-10   facebook              68            2445             62.0
52  2026-01-11   facebook              70            2445             64.0
57  2026-01-12   facebook              72            2445             66.0
61  2026-01-13   facebook              74            2445             68.0
66  2026-01-14   facebook              76            2445             70.0
72  2026-01-15   facebook              78            2445             72.0
77  2026-01-16   facebook              80            2445             74.0
81  2026-01-17   facebook              82            2445             76.0
87  2026-01-18   facebook              84            2445             78.0
91  2026-01-19   facebook              86            2445             80.0
97  2026-01-20   facebook              88            2445             82.0

In [ ]:
df['cumulative_sum'] = df.groupby('ad_channel')['daily_visitors'].transform(lambda x: x.expanding().sum())
df.sort_values(['ad_channel', 'date']).head(20)
# А прикол expandinga в том, что он берет и с самого начала накапливает значения в себе - Собирательный эффект

,date,ad_channel,daily_visitors,total_visitors,rolling_average,cumulative_sum
1,2026-01-01,facebook,50,2445,NaN,50.0
6,2026-01-02,facebook,52,2445,NaN,102.0
11,2026-01-03,facebook,54,2445,NaN,156.0
16,2026-01-04,facebook,56,2445,NaN,212.0
21,2026-01-05,facebook,58,2445,NaN,270.0
27,2026-01-06,facebook,60,2445,NaN,330.0
31,2026-01-07,facebook,62,2445,56.0,392.0
37,2026-01-08,facebook,64,2445,58.0,456.0
42,2026-01-09,facebook,66,2445,60.0,522.0
46,2026-01-10,facebook,68,2445,62.0,590.0
52,2026-01-11,facebook,70,2445,64.0,660.0
57,2026-01-12,facebook,72,2445,66.0,732.0
61,2026-01-13,facebook,74,2445,68.0,806.0
66,2026-01-14,facebook,76,2445,70.0,882.0
72,2026-01-15,facebook,78,2445,72.0,960.0
77,2026-01-16,facebook,80,2445,74.0,1040.0
81,2026-01-17,facebook,82,2445,76.0,1122.0
87,2026-01-18,facebook,84,2445,78.0,1206.0
91,2026-01-19,facebook,86,2445,80.0,1292.0
97,2026-01-20,facebook,88,2445,82.0,1380.0

In [ ]:
# shift - По сути помогает нам получить данные в новых строках, взятые из предыдущих или следующих строк 
# foo = df.head()[['daily_visitors']]
# foo['yesterday_visitors'] = foo['daily_visitors'].shift(1)
# foo['result'] = foo['daily_visitors'] - foo['yesterday_visitors']
# foo

df['yesterday_visitors'] = df.groupby('ad_channel')['daily_visitors'].shift(1)
df['result'] = df['daily_visitors'] - df['yesterday_visitors']
df.sort_values(['ad_channel', 'date']).head(20)
df

,date,ad_channel,daily_visitors,total_visitors,rolling_average,cumulative_sum,yesterday_visitors,result
0,2026-01-01,google,52,2472,NaN,52.0,NaN,NaN
1,2026-01-01,facebook,50,2445,NaN,50.0,NaN,NaN
2,2026-01-01,youtube,55,2562,NaN,55.0,NaN,NaN
3,2026-01-01,instagram,53,2515,NaN,53.0,NaN,NaN
4,2026-01-01,influencers,51,2470,NaN,51.0,NaN,NaN
...,...,...,...,...,...,...,...,...
150,2026-01-31,google,98,2472,99.142857,2472.0,100.0,-2.0
151,2026-01-31,facebook,100,2445,99.000000,2445.0,99.0,1.0
152,2026-01-31,instagram,99,2515,98.714286,2515.0,98.0,1.0
153,2026-01-31,youtube,100,2562,98.714286,2562.0,100.0,0.0
154,2026-01-31,influencers,98,2470,99.142857,2470.0,100.0,-2.0

In [40]:
df.sort_values(['ad_channel', 'date']).head(20)

,date,ad_channel,daily_visitors,total_visitors,rolling_average,cumulative_sum,yesterday_visitors,result
1,2026-01-01,facebook,50,2445,NaN,50.0,NaN,NaN
6,2026-01-02,facebook,52,2445,NaN,102.0,50.0,2.0
11,2026-01-03,facebook,54,2445,NaN,156.0,52.0,2.0
16,2026-01-04,facebook,56,2445,NaN,212.0,54.0,2.0
21,2026-01-05,facebook,58,2445,NaN,270.0,56.0,2.0
27,2026-01-06,facebook,60,2445,NaN,330.0,58.0,2.0
31,2026-01-07,facebook,62,2445,56.0,392.0,60.0,2.0
37,2026-01-08,facebook,64,2445,58.0,456.0,62.0,2.0
42,2026-01-09,facebook,66,2445,60.0,522.0,64.0,2.0
46,2026-01-10,facebook,68,2445,62.0,590.0,66.0,2.0
52,2026-01-11,facebook,70,2445,64.0,660.0,68.0,2.0
57,2026-01-12,facebook,72,2445,66.0,732.0,70.0,2.0
61,2026-01-13,facebook,74,2445,68.0,806.0,72.0,2.0
66,2026-01-14,facebook,76,2445,70.0,882.0,74.0,2.0
72,2026-01-15,facebook,78,2445,72.0,960.0,76.0,2.0
77,2026-01-16,facebook,80,2445,74.0,1040.0,78.0,2.0
81,2026-01-17,facebook,82,2445,76.0,1122.0,80.0,2.0
87,2026-01-18,facebook,84,2445,78.0,1206.0,82.0,2.0
91,2026-01-19,facebook,86,2445,80.0,1292.0,84.0,2.0
97,2026-01-20,facebook,88,2445,82.0,1380.0,86.0,2.0

In [ ]:
# DZ 1
df['Rolling_Avg'] = df['Stock_Price'].rolling(5).mean().round(2)
print(df.to_string(index=None))

In [ ]:
# DZ 2
df['Average_Sales'] = df.groupby('Region')['Sales'].transform(lambda x: x.mean())
df['Normalized_Sales'] = df['Sales'] / df['Average_Sales']
print(df.round(2).to_string(index=None))

In [ ]:
# DZ 3
df['Cumulative_Avg_Sales'] = df['Sales'].transform(lambda x: x.expanding().mean()).round(2)
print(df.to_string(index=None))

In [ ]:
# DZ 4
df['Daily_Change'] = df['Sales'] - df.groupby('Product_Name')['Sales'].shift(1) 
print(df.to_string(index=None))